<!DOCTYPE html>
<html lang="ko" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
    <meta name="description" content=""/>
    <meta name="keywords" content=""/>
</head>
<body>
<div class="container" style="width: 45rem; border: 0.1rem solid #ced4da;">
    <#include "${lang}/${template}.ftlh"/>
    <#include "${lang}/footer.ftlh"/>
</div>
</body>
</html>
